// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubAgentSpawnParams = {
/**
 * Loaded parent thread whose spawn tree should own the new child thread.
 */
parentThreadId: string,
/**
 * Optional nickname shown in thread pickers for the spawned child thread.
 */
agentNickname?: string | null,
/**
 * Optional role shown in thread pickers for the spawned child thread.
 */
agentRole?: string | null, };
