// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadDreamStartResponse = { memoryRoot: string, retrospectivePath: string, updatedAgentsPath: string, updatedSkillPaths: Array<string>, nextSessionHint: string, };
